version: '3.8'

services:
  nestjs-api:
    container_name: customer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/src/app
      - /src/app/node_modules
    command: npm run start:prod
